name: challenge

on:
  push:
    branches:
      - main2
  pull_request:
    branches:
      - main2

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2    
    - name: Step two
      run: "Get-Date"
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date
  job4:
    needs: [job1, job2, job3]
    name: Fourth job
    runs-on: ubuntu-20.04
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: date    
